backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "src/assets/images/articles/" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images/articles/" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

display_url: https://kizombaszeged.hu/

collections:
  - name: "article" # Used in routes, e.g., /admin/collections/article
    label: "Article" # Used in the UI
    folder: "src/posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "string"}
      - {label: "DateNew", name: "date", widget: "date"}
      - {label: "Short excerpt", name: "excerpt", widget: "text"}
      - {label: "Topic", name: "topic", widget: "select", options: ["tánc", "zene", "kultúra"], multiple: false}
      - {label: "Cover image filename with extension", name: "coverImage", widget: "image"}
      - {label: "Body of the post", name: "body", widget: "markdown"}
  - name: "data"
    label: "Data"
    description: We store the workshop information in a YAML file
    files:
      - label: "Workshop"
        name: "workshop"
        file: "src/data/workshop.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Place and time, name: subtitle, widget: string}
          - {label: Facebook link, name: link, widget: string}

